name: Build and Deploy

on:
  issues:
    types:
      - opened

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Display github event details
      run: |
        echo $GITHUB_EVENT_PATH
        cat $GITHUB_EVENT_PATH
