name: Build and Deploy

on:
  issues:
    types:
      - opened
  pull_request:
    branches:
      - master
      - release/**
    types:
      - opened
      - synchronize
      - closed
  push:
    branches:
      - master
      - release/**

env:
  GITHUB_REPO: ${{ github.event.repository.name }}
  GITHUB_EVENT: ${{ github.event_name }}
  GITHUB_REF: ${{ github.ref }}
  GITHUB_HEAD_REF: ${{ github.head_ref }}
  GITHUB_BASE_REF: ${{ github.base_ref }}
  GITHUB_WORKSPACE: ${{ github.workspace }}
  GITHUB_ACTION: ${{ github.action }}
  
jobs:
  job1:
    name: Job1
    runs-on: ubuntu-18.04
    
    outputs:
      can-build: ${{ steps.id1.outputs.staging || steps.id1.outputs.alpha }}
      
    steps:
    - name: Environment
      id: id1
      run: |
        echo "::set-output name=staging::false"
        echo "::set-output name=alpha::false"

    - name: Checkout
      uses: actions/checkout@v2

  job2:
    name: Job2
    runs-on: ubuntu-18.04
      
    steps:
    - name: Checkout Ops
      uses: actions/checkout@v2

