name: Build and Deploy

on:
  push

env:
  GITHUB_REPO: ${{ github.event.repository.name }}
  GITHUB_EVENT: ${{ github.event_name }}
  GITHUB_REF: ${{ github.ref }}
  GITHUB_HEAD_REF: ${{ github.head_ref }}
  GITHUB_BASE_REF: ${{ github.base_ref }}
  GITHUB_WORKSPACE: ${{ github.workspace }}
  GITHUB_ACTION: ${{ github.action }}
  
jobs:
  job1:
    name: Job1
    runs-on: ubuntu-18.04
      
    steps:
    - name: Checkout Ops
      uses: actions/checkout@v2
      
    - name: Environment
      run: |
        echo "::set-env name=tag::${GITHUB_SHA::8}$(date +%FT%H-%M)"

