name: Build and Deploy

on:
  issues:
    types:
      - opened

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-18.04
    
    if: startsWith(github.event.issue.title, 'deploy')
      
    steps:
    
    - name: Environment
      run: echo "::set-env name=GIT_BRANCH::$(echo ${{ github.event.issue.title }} | sed 's/[Dd]eploy //g')"

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.issue.title }}


