name: Build and Deploy

on:
  issues:
    types:
      - opened

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-18.04
    
    if: startsWith(github.event.issue.title, 'deploy')
      
    steps:
    
    - name: Environment
      run: echo "::set-env name=GITHUB_BRANCH::$(echo $ISSUE_TITLE | sed 's/[Dd]eploy //g')"
      env:
        ISSUE_TITLE: ${{ github.event.issue.title }}

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: $GITHUB_BRANCH

    - name: Display github event details
      run: |
        echo $ISSUE_TITLE | sed 's/[Dd]eploy //g'
        cat $GITHUB_EVENT_PATH
      env:
        ISSUE_TITLE: ${{ github.event.issue.title }}
