name: Build and Deploy

on:
  issues:
    types:
      - opened

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-18.04
    
    if: startsWith(github.event.issue.title, 'deploy')
    
    env:
      DEPLOY_BRANCH: ${{ echo github.event.issue.title | sed 's/[Dd]eploy //g' }}
      
    steps:
    
    - name: Setup
      run: echo "::set-env GITHUB_BRANCH::${ echo github.event.issue.title | sed 's/[Dd]eploy //g'}"

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: $GITHUB_BRANCH

    - name: Display github event details
      run: |
        echo $ISSUE_TITLE | sed 's/[Dd]eploy //g'
        cat $GITHUB_EVENT_PATH
      env:
        ISSUE_TITLE: ${{ github.event.issue.title }}
