name: Build and Deploy

on:
  issues:
    types:
      - opened

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-18.04
   
    if: startsWith(github.event.issue.title, 'deploy')
      
    steps:
    - name: Environment
      run: echo "::set-env name=GIT_BRANCH::$(echo ${{ github.event.issue.title }} | sed 's/^deploy //I')"

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ env.GIT_BRANCH }}
        path: main
        
    - name: Checkout Ops
      uses: actions/checkout@v2
      with:
        repository: ${{ format('{0}-ops', github.repository) }}
        token: ${{ secrets.TOKEN }}
        path: ops

