name: Build and Deploy

on:
  issues:
    types:
      - opened
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - closed
  push:
    branches: 
      - master

env:
  GITHUB_REPO: ${{ github.event.repository.name }}
  GITHUB_EVENT: ${{ github.event_name }}
  GITHUB_REF: ${{ github.ref }}
  GITHUB_HEAD_REF: ${{ github.head_ref }}
  GITHUB_BASE_REF: ${{ github.base_ref }}
  GITHUB_WORKSPACE: ${{ github.workspace }}
  GITHUB_ACTION: ${{ github.action }}
  GCR_REPO: ${{ format('{0}/{1}', secrets.GCR_PROJECT, github.event.repository.name) }}
  
jobs:
  job1:
    name: Job1
    runs-on: ubuntu-18.04
      
    steps:
    - name: Environment
      run: |
        echo "::set-env name=tag::${GITHUB_SHA::8}-$(date +%FT%H-%M)"
  
    - name: Checkout Ops
      uses: actions/checkout@v2
  
  job2:
    name: Job2
    runs-on: ubuntu-18.04
      
    steps:
    - name: Environment
      run: |
        echo "::set-env name=tag::${GITHUB_SHA::8}-$(date +%FT%H-%M)"
  
    - name: Checkout Ops
      uses: actions/checkout@v2

