name: Build and Deploy

on:
  issues:
    types:
      - opened
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - closed

env:
  GITHUB_REPO: ${{ github.event.repository.name }}
  GITHUB_EVENT: ${{ github.event_name }}
  GITHUB_REF: ${{ github.ref }}
  GITHUB_HEAD_REF: ${{ github.head_ref }}
  GITHUB_BASE_REF: ${{ github.base_ref }}
  GITHUB_WORKSPACE: ${{ github.workspace }}
  GITHUB_ACTION: ${{ github.action }}
  
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-18.04
      
    steps:
    - name: Environment
      #if: startsWith(github.event.issue.title, 'deploy')
      run: |
        #echo "::set-env name=TAG::$(echo ${{ env.GITHUB_HEAD_REF }} | sed 's/^releases\///I')"
        echo ${{ env.TAG }}
        echo ${{ github.event.action }}

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ env.GIT_BRANCH }}
        path: main
        
    - name: SSH File
      id: write_file
      uses: timheuer/base64-to-file@v1.0.3
      with:
        fileName: 'ssh_key'
        encodedString: ${{ secrets.SSH_KEY }}
        
    - run: echo "::set-env name=SSH_KEY::$(cat ${{ steps.write_file.outputs.filePath }}"
        
    - name: Checkout Ops
      uses: actions/checkout@v2
      env:
        SSH_KEY: ${{ env.SSH_KEY }}
      with:
        repository: ${{ format('{0}-ops', github.repository) }}
        token: ${{ secrets.TOKEN }}
        path: ops

