name: Close Issues

on:
  pull_request:
  label:

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-18.04
      
    steps:
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

  danger:
    name: Linter
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout App
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Cache Gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('.github/Gemfile') }}

    - name: Danger Validation
      uses: MeilCli/danger-action@v4
      with:
        plugins_file: '.github/Gemfile'
        install_path: 'vendor/bundle'
        danger_file: '.github/Dangerfile'
        danger_id: 'danger-pr'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  merge:
    name: Automerge
    runs-on: ubuntu-18.04

    needs: [job1,danger]
    if: ${{ success() }}

    steps:
    - name: Checkout App
      uses: actions/checkout@v2

    - name: Automerge
      uses: pascalgn/automerge-action@v0.9.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
